############################################################################## 
/home/dm/myprojects/python27-env/src/my/pelican
/home/dm/myprojects/python27-env/bin
/home/dm/myprojects/python27-env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg
/home/dm/myprojects/python27-env/src/my/feedgenerator-py3k
/home/dm/myprojects/python27-env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg
/home/dm/myprojects/python27-env/lib/python2.7
/home/dm/myprojects/python27-env/lib/python2.7/plat-linux2
/home/dm/myprojects/python27-env/lib/python2.7/lib-tk
/home/dm/myprojects/python27-env/lib/python2.7/lib-old
/home/dm/myprojects/python27-env/lib/python2.7/lib-dynload
/usr/lib/python2.7
/usr/lib/python2.7/plat-linux2
/usr/lib/python2.7/lib-tk
/home/dm/myprojects/python27-env/local/lib/python2.7/site-packages 
##############################################################################
