suite={'TIMEZONE': 'Europe/Paris', 'RELATIVE_URLS': True, 'DEFAULT_METADATA': (('yeah', 'it is'),), 'FILES_TO_COPY': (('extra/robots.txt', 'robots.txt'),), 'DEFAULT_ORPHANS': 0, 'FEED_DOMAIN': '', 'DIRECT_TEMPLATES': ('index', 'tags', 'categories', 'archives'), 'GITHUB_URL': 'http://github.com/ametaireau/', 'DELETE_OUTPUT_DIRECTORY': False, 'PAGE_DIR': 'pages', 'FEED_MAX_ITEMS': '', 'PATH': '/home/dm/myprojects/python27-env/src/my/pelican/samples', 'DEFAULT_DATE': (2012, 3, 2, 14, 1, 1), 'TAG_CLOUD_MAX_ITEMS': 100, 'WITH_FUTURE_DATES': True, 'CATEGORY_SAVE_AS': 'category/{slug}.html', 'LINKS': (('Biologeek', 'http://biologeek.org'), ('Filyb', 'http://filyb.info/'), ('Libert-fr', 'http://www.libert-fr.com'), ('N1k0', 'http://prendreuncafe.com/blog/'), (u'Tarek Ziad\xe9', 'http://ziade.org/blog'), ('Zubin Mithra', 'http://zubin71.wordpress.com/')), 'ARTICLE_LANG_SAVE_AS': '{slug}-{lang}.html', 'DEFAULT_LANG': 'en', 'PAGE_LANG_SAVE_AS': 'pages/{slug}-{lang}.html', 'AUTHOR': u'Alexis M\xe9taireau', 'PAGE_EXCLUDES': (), 'ARTICLE_PERMALINK_STRUCTURE': '', 'MARKUP': ('rst', 'md'), 'LESS_GENERATOR': False, 'FEED_RSS': 'feeds/all.rss.xml', 'ARTICLE_EXCLUDES': ('pages',), 'LOCALE': 'C', 'ARTICLE_URL': '{slug}.html', 'TAG_CLOUD_STEPS': 4, 'ARTICLE_SAVE_AS': '{slug}.html', 'PLUGINS': [], 'DEFAULT_PAGINATION': 4, 'PAGE_URL': 'pages/{slug}.html', 'SOCIAL': (('twitter', 'http://twitter.com/ametaireau'), ('lastfm', 'http://lastfm.com/user/akounet'), ('github', 'http://github.com/ametaireau')), 'JINJA_EXTENSIONS': [], 'STATIC_PATHS': ['pictures'], 'DISQUS_SITENAME': 'blog-notmyidea', 'WEBASSETS': False, 'DEFAULT_CATEGORY': 'misc', 'ARTICLE_LANG_URL': '{slug}-{lang}.html', 'TAG_SAVE_AS': 'tag/{slug}.html', 'PAGINATED_DIRECT_TEMPLATES': ('index',), 'PAGE_LANG_URL': 'pages/{slug}-{lang}.html', 'TRANSLATION_FEED': 'feeds/all-%s.atom.xml', 'TYPOGRIFY': False, 'CSS_FILE': 'main.css', 'CATEGORY_FEED_ATOM': 'feeds/%s.atom.xml', 'AUTHOR_URL': u'author/{slug}.html', 'CATEGORY_URL': 'category/{slug}.html', 'DEFAULT_DATE_FORMAT': '%a %d %B %Y', 'AUTHOR_SAVE_AS': u'author/{slug}.html', 'REVERSE_CATEGORY_ORDER': True, 'TAG_URL': 'tag/{slug}.html', 'SUMMARY_MAX_LENGTH': 50, 'DATE_FORMATS': {}, 'ARTICLE_DIR': '', 'SITEURL': 'http://blog.notmyidea.org', 'PDF_GENERATOR': False, 'PAGE_SAVE_AS': 'pages/{slug}.html', 'DISPLAY_PAGES_ON_MENU': True, 'THEME': '/home/dm/myprojects/python27-env/src/my/pelican/pelican/themes/notmyidea', 'PELICAN_CLASS': 'pelican.Pelican', 'SITENAME': u"Alexis' log", 'THEME_STATIC_PATHS': ['static'], 'OUTPUT_PATH': '/home/dm/myprojects/python27-env/src/my/pelican/samples/output', 'FEED_ATOM': 'feeds/all.atom.xml', 'DEFAULT_STATUS': 'published', 'CATEGORY_FEED_RSS': 'feeds/%s.rss.xml', 'NEWEST_FIRST_ARCHIVES': True}
single={'RELATIVE_URLS': True, 'DEFAULT_METADATA': (('yeah', 'it is'),), 'FILES_TO_COPY': (('extra/robots.txt', 'robots.txt'),), 'DEFAULT_ORPHANS': 0, 'TIMEZONE': 'Europe/Paris', 'DIRECT_TEMPLATES': ('index', 'tags', 'categories', 'archives'), 'GITHUB_URL': 'http://github.com/ametaireau/', 'DELETE_OUTPUT_DIRECTORY': False, 'PAGE_DIR': 'pages', 'FEED_MAX_ITEMS': '', 'PATH': '/home/dm/myprojects/python27-env/src/my/pelican/samples', 'DEFAULT_DATE': (2012, 3, 2, 14, 1, 1), 'TAG_CLOUD_MAX_ITEMS': 100, 'WITH_FUTURE_DATES': True, 'CATEGORY_SAVE_AS': 'category/{slug}.html', 'LINKS': (('Biologeek', 'http://biologeek.org'), ('Filyb', 'http://filyb.info/'), ('Libert-fr', 'http://www.libert-fr.com'), ('N1k0', 'http://prendreuncafe.com/blog/'), (u'Tarek Ziad\xe9', 'http://ziade.org/blog'), ('Zubin Mithra', 'http://zubin71.wordpress.com/')), 'ARTICLE_LANG_SAVE_AS': '{slug}-{lang}.html', 'DEFAULT_LANG': 'en', 'PAGE_LANG_SAVE_AS': 'pages/{slug}-{lang}.html', 'AUTHOR': u'Alexis M\xe9taireau', 'PAGE_EXCLUDES': (), 'ARTICLE_PERMALINK_STRUCTURE': '', 'MARKUP': ('rst', 'md'), 'LESS_GENERATOR': False, 'FEED_RSS': 'feeds/all.rss.xml', 'ARTICLE_EXCLUDES': ('pages',), 'LOCALE': 'C', 'ARTICLE_URL': '{slug}.html', 'TAG_CLOUD_STEPS': 4, 'ARTICLE_SAVE_AS': '{slug}.html', 'PLUGINS': [], 'DEFAULT_PAGINATION': 4, 'PAGE_URL': 'pages/{slug}.html', 'SOCIAL': (('twitter', 'http://twitter.com/ametaireau'), ('lastfm', 'http://lastfm.com/user/akounet'), ('github', 'http://github.com/ametaireau')), 'JINJA_EXTENSIONS': [], 'STATIC_PATHS': ['pictures'], 'DISQUS_SITENAME': 'blog-notmyidea', 'WEBASSETS': False, 'FEED_DOMAIN': 'http://blog.notmyidea.org', 'DEFAULT_CATEGORY': 'misc', 'ARTICLE_LANG_URL': '{slug}-{lang}.html', 'TAG_SAVE_AS': 'tag/{slug}.html', 'PAGINATED_DIRECT_TEMPLATES': ('index',), 'PAGE_LANG_URL': 'pages/{slug}-{lang}.html', 'TRANSLATION_FEED': 'feeds/all-%s.atom.xml', 'TYPOGRIFY': False, 'CSS_FILE': 'main.css', 'CATEGORY_FEED_ATOM': 'feeds/%s.atom.xml', 'AUTHOR_URL': u'author/{slug}.html', 'CATEGORY_URL': 'category/{slug}.html', 'DEFAULT_DATE_FORMAT': '%a %d %B %Y', 'AUTHOR_SAVE_AS': u'author/{slug}.html', 'REVERSE_CATEGORY_ORDER': True, 'TAG_URL': 'tag/{slug}.html', 'SUMMARY_MAX_LENGTH': 50, 'DATE_FORMATS': {}, 'ARTICLE_DIR': '', 'SITEURL': 'http://blog.notmyidea.org', 'PDF_GENERATOR': False, 'PAGE_SAVE_AS': 'pages/{slug}.html', 'DISPLAY_PAGES_ON_MENU': True, 'THEME': '/home/dm/myprojects/python27-env/src/my/pelican/pelican/themes/notmyidea', 'PELICAN_CLASS': 'pelican.Pelican', 'SITENAME': u"Alexis' log", 'THEME_STATIC_PATHS': ['static'], 'OUTPUT_PATH': '/home/dm/myprojects/python27-env/src/my/pelican/samples/output', 'FEED_ATOM': 'feeds/all.atom.xml', 'DEFAULT_STATUS': 'published', 'CATEGORY_FEED_RSS': 'feeds/%s.rss.xml', 'NEWEST_FIRST_ARCHIVES': True}

kk_suite = set(suite.keys())
kk_single = set(single.keys())

assert(kk_single == kk_suite)

for k in sorted(kk_suite):
    if suite[k] != single[k]:
        print "{0:30}: suite={1:30}, single={2}".format(k, suite[k], single[k])
